### ISSUE TITLE
ideas for this project

### ISSUE THREAD

**Issue by octanejohn** [Gab-ani/Godot-Parkour-And-Advanced-Movement#1]
there are multible active repos but the main ones is https://github.com/GuilhermeGSousa/godot-motion-matching

for more ideas is the godot dev chat https://chat.godotengine.org/channel/animation

**Comment by Gab-ani** [comment]
Thanks!)
Well, I am aware of motion matching being a thing, and implementing it in godot is certainly a nice end goal to have for a project. But I don't think I will try to implement something like it, as motion matching is a technology that thrives in an environment where you have much more animations than planned actions to implement. And in an indie environment I usually have less animations than actions I want to implement т_т.
But as an inspiration source, yes, thanks, I'll look into that!
